export const bugs = [
  {
    id: 124,
    title: "Login form validation error on special characters",
    description:
      "When entering special characters in the login form, the validation error message is not displayed correctly.",
    severity: "high",
    status: "in-progress",
    assignedTo: "John Doe",
    reportedBy: "Jane Smith",
    dateReported: "Mar 29, 2025",
    lastUpdated: "Mar 30, 2025",
  },
  {
    id: 123,
    title: "Dashboard charts not rendering in Safari",
    description: "The dashboard charts are not rendering correctly in Safari browser. They appear blank.",
    severity: "medium",
    status: "open",
    assignedTo: "Alex Johnson",
    reportedBy: "Sarah Williams",
    dateReported: "Mar 28, 2025",
    lastUpdated: "Mar 28, 2025",
  },
  {
    id: 122,
    title: "User profile image upload fails with large files",
    description: "When trying to upload profile images larger than 5MB, the upload fails without any error message.",
    severity: "low",
    status: "resolved",
    assignedTo: "John Doe",
    reportedBy: "Mike Brown",
    dateReported: "Mar 27, 2025",
    lastUpdated: "Mar 29, 2025",
  },
  {
    id: 121,
    title: "API timeout on large data requests",
    description:
      "The API times out when requesting large datasets. This happens consistently when fetching more than 1000 records.",
    severity: "critical",
    status: "open",
    assignedTo: "Sarah Williams",
    reportedBy: "Jane Smith",
    dateReported: "Mar 26, 2025",
    lastUpdated: "Mar 27, 2025",
  },
  {
    id: 120,
    title: "Notification bell not showing count",
    description: "The notification bell icon is not showing the count of unread notifications.",
    severity: "low",
    status: "in-progress",
    assignedTo: "Alex Johnson",
    reportedBy: "John Doe",
    dateReported: "Mar 25, 2025",
    lastUpdated: "Mar 26, 2025",
  },
  {
    id: 119,
    title: "Export to PDF feature generates corrupted files",
    description: "When exporting reports to PDF, the generated files are corrupted and cannot be opened.",
    severity: "high",
    status: "open",
    assignedTo: null,
    reportedBy: "Mike Brown",
    dateReported: "Mar 24, 2025",
    lastUpdated: "Mar 24, 2025",
  },
  {
    id: 118,
    title: "Search functionality returns incorrect results",
    description: "The global search functionality is returning incorrect results when searching for specific terms.",
    severity: "medium",
    status: "resolved",
    assignedTo: "John Doe",
    reportedBy: "Jane Smith",
    dateReported: "Mar 23, 2025",
    lastUpdated: "Mar 25, 2025",
  },
  {
    id: 117,
    title: "Mobile menu not closing on item selection",
    description: "On mobile devices, the navigation menu doesn't close automatically when a menu item is selected.",
    severity: "low",
    status: "closed",
    assignedTo: "Sarah Williams",
    reportedBy: "Alex Johnson",
    dateReported: "Mar 22, 2025",
    lastUpdated: "Mar 24, 2025",
  },
  {
    id: 116,
    title: "Password reset emails not being sent",
    description: "Users are not receiving password reset emails when requested. No error is shown in the UI.",
    severity: "critical",
    status: "resolved",
    assignedTo: "Alex Johnson",
    reportedBy: "Mike Brown",
    dateReported: "Mar 21, 2025",
    lastUpdated: "Mar 23, 2025",
  },
  {
    id: 115,
    title: "Data table pagination not working",
    description:
      "The pagination controls in the data tables are not functioning correctly. Cannot navigate to next pages.",
    severity: "medium",
    status: "in-progress",
    assignedTo: "John Doe",
    reportedBy: "Jane Smith",
    dateReported: "Mar 20, 2025",
    lastUpdated: "Mar 22, 2025",
  },
  {
    id: 114,
    title: "Dark mode toggle affects performance",
    description:
      "Toggling between light and dark mode causes significant performance degradation, especially on older devices.",
    severity: "low",
    status: "open",
    assignedTo: null,
    reportedBy: "Sarah Williams",
    dateReported: "Mar 19, 2025",
    lastUpdated: "Mar 19, 2025",
  },
  {
    id: 113,
    title: "Form submission duplicates data",
    description: "Submitting forms sometimes creates duplicate entries in the database. This happens randomly.",
    severity: "high",
    status: "open",
    assignedTo: "Sarah Williams",
    reportedBy: "John Doe",
    dateReported: "Mar 18, 2025",
    lastUpdated: "Mar 18, 2025",
  },
]

